github: [abhishekdemouser]  # Replace with your GitHub username if sponsoring is enabled
#patreon: abhishekdemouser   # Replace with your Patreon username (if available)
#ko_fi: abhishekdemouser     # Replace with your Ko-fi username (optional)

custom:
  - 'https://abhishekdemouser.wixsite.com/ens-domain-is-nuture'
  - 'https://abhishekdemouser.wixsite.com/ens-domain-is-nuture/blog'

